(client): TeamRow component finished
13th-office/IBM-SkillBoard pull request #73
Opened 2023-04-24 19:06 UTC by MrFiddle

### Components
- `TeamRow.tsx`
    - Row part of a future component called TeamTable.
  
- `types.ts`
    - Attribute added to 'User' interface.
 
- `MyTeamScreen.tsx`
    - Temporal dummy data added in top of component to render the TeamRow component.
    - Change Header title to 'My Teams' instead of 'My Team'.  

- `CertificationRow.tsx`
    - Change items position to align them with the top bar of the table.
 
- `Header.tsx`
    - Changed font-weight attribute to the text of it to a heavier one. (ik it's not part of what I had to do but me dio fomo srry)  

### Description
- `TeamRow.tsx` component created, it renders a card that contains an employee, with its name, role and a button to visit their profile.

## Test Plan
![Captura de pantalla 2023-04-24 130607](https://user-images.githubusercontent.com/25809332/234092096-321db018-7f04-475a-825d-3cefe347c5a2.png)

2023-04-24 20:33 UTC, EvilDao-RG commented on client/lib/types.ts
Este atributo no rompe el componente del sidebar? Mejor crea otro tipo, que sea Employee

2023-04-24 20:34 UTC, EvilDao-RG requested changes
Regresa el tipo User a como estaba y pon otro tipo llamado employee

2023-04-24 23:07 UTC, emiliogonmar2002 commented on client/lib/types.ts
Dejarlo en el mismo interface, esa info es de todo el usuario

2023-04-25 00:50 UTC, emiliogonmar2002 commented on client/lib/types.ts
> +  rol: string;
role

2023-04-25 04:47 UTC, emiliogonmar2002 approved these changes
LGTM

2023-04-25 14:55 UTC, merged